### ISSUE TITLE
Decimal delays

### ISSUE THREAD

**Issue by MarkAYoder** [deepakkarki/pruspeak#4]
I'd like a delay of less than 1ms, so I tried:

SCRIPT
SET DIO[0], 1
WAIT 0.1
SET DIO[0], 0
WAIT 0.1
GOTO 0
ENDSCRIPT
RUN

I got the following:

Initializing PRU Speak
Illegal character '.'
Traceback (most recent call last):
  File "./my_example_copy.py", line 87, in <module>
    ret = pru_speak.execute_instruction(EX6)
  File "/root/pruspeak/src/userspace_lib/pru_speak/pruspeak.py", line 92, in execute_instruction
    byte_code  = parser.parse(inst)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 921, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python2.7/dist-packages/ply/lex.py", line 387, in token
    raise LexError("Scanning error. Illegal character '%s'" % (lexdata[lexpos]), lexdata[lexpos:])
ply.lex.LexError: Scanning error. Illegal character '.'
PRU Speak object deleted

BOTSPEAK allows decimal delays, does PRUSPEAK?

--Mark

**Comment by shubhi1407** [comment]
WAIT instructions can now take uS delays. Added float tokenizing to bs_lex. Sending pull request.

![img_0170](https://cloud.githubusercontent.com/assets/10467241/6901333/7ee5cd90-d6da-11e4-8385-c00bc373ed8b.JPG)
![img_0171](https://cloud.githubusercontent.com/assets/10467241/6901335/7f1e0b06-d6da-11e4-98c1-64f1f4d8b475.JPG)
![img_0172](https://cloud.githubusercontent.com/assets/10467241/6901334/7f1c2354-d6da-11e4-9755-cf69f526cb59.JPG)
![img_0173](https://cloud.githubusercontent.com/assets/10467241/6901336/7f209c72-d6da-11e4-9ee5-02e0a4ac247d.JPG)
